<?php
return array(
    'company',
    'gyoukai',
    'job_class',
    'title',
    'necessary',
    'salary_low',
    'salary_high',
    'contents',
    'workplace',
    'employment_status',
    'recommendation',
    'test_term',
    'salary_detail',
    'working_time',
    'overtime',
    'overtime_pay',
    'insurance',
    'welfare',
    'holiday',
    'selection_contents'
);
